# ========================================
# DOCKER COMPOSE PRODUCTION - AL-IMAM
# ========================================
version: '3.8'

services:
  postgres-ulul:
    image: postgres:15-alpine
    container_name: pp-ululalbaab-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin_ulul}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-db_ululalbaab_prod}
    ports:
      - "5436:5432" # Pindah port lagi demi keamanan & isolasi
    volumes:
      - postgres_ululalbaab_prod_data:/var/lib/postgresql/data

  app-alimam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://pesantren-alimam.com}
        NEXTAUTH_URL: ${NEXTAUTH_URL:-https://pesantren-alimam.com}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretkeyalimam2024}
    container_name: pp-alimam-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-https://pesantren-alimam.com}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-supersecretkeyalimam2024}
      FAGI_WA_KEY: ${FAGI_WA_KEY}
    volumes:
      - storage_alimam_data:/app/public/storage
      - storage_alimam_data:/app/storage_data

volumes:
  postgres_ululalbaab_prod_data:
  storage_alimam_data:
